### ISSUE TITLE
Rename to ZIO Delegate?

### ISSUE THREAD

**Issue by jdegoes** [mschuwalow/delegate#1]

**Comment by mschuwalow** [comment]
Yeah that makes sense. What about the artifactId -- delegate or zio-delegate?

**Comment by neko-kai** [comment]
Well, if you rename it to zio-delegate, I guess the artifact should also be zio-delegate, just to be consistent, I think...

**Comment by mschuwalow** [comment]
Ok. Then I'll go ahead and rename this while there aren't many links to break

**Comment by mschuwalow** [comment]
@neko-kai @jdegoes  I don't think I have the permission to modify the repository.
Could one of you rename it to zio/zio-delegate? :pray:

**Comment by jdegoes** [comment]
Yes, I'd do artifact name too.

Done on the rename! 👍

**Comment by mschuwalow** [comment]
> Yes, I'd do artifact name too.
> 
> Done on the rename!

Thanks! Artifact, etc. have been renamed as well
