### ISSUE TITLE
Migrate to zio-macros

### ISSUE THREAD

**Issue by ioleo** [mschuwalow/delegate#4]
@mschuwalow [zio-macros](https://github.com/zio/zio-macros) is almost ready, I've already started releasing (on `v0.1.1-2` now)

I've still got one issue with `2.13` I had no time yet to investigate, so currently I'm only releasing for `2.11` and `2.12`, so I guess you might want to hold until I fix it.

Other than that, I believe we should:
- [x] migrate `zio-delegate` to `zio-macros` as `zio-macros-delegate`
- [x] add @mschuwalow as admin to `zio-macros` (I guess @ghostdogpr can help here)

Perhaps you could join discord `#zio-macros` channel https://discord.gg/tS3ePv and we could discuss this in detail?

**Comment by mschuwalow** [comment]
Sounds good. Let's continue this on discord

**Comment by mijicd** [comment]
@ioleo Granted admin permissions to @mschuwalow

**Comment by mschuwalow** [comment]
@ioleo @mijicd thanks
